<?php
$Gestalt6sp = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>

<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">

<plist version=\"1.0\">

<dict>

	<key>CacheUUID</key>

	<string>6D7D99F5-43BA-451A-A4A1-CFA228EDABE9</string>

	<key>CacheData</key>

	<data>

	AAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAA

	AAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAA

	AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAA

	AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAABAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAA

	AAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAQAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAADAAA

	AQAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAA

	AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAB

	AAAAAAAAAAOAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA

	AAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA

	AAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC3zOEAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAA

	AAAAAAAAAAAAAOjn5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAA

	AAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAA

	AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAKAAAAAAAAAGQA

	AAAAAAAA5AAAAAAAAADkAAAAAAAAANAHAAAAAAAAAAAAAAAAAAABAAAAAAAAAAoAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAA

	AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAPoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAeAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAA

	AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAA

	AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA

	AAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAA

	AQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAACamZk+AAAAAAAAAAAAAAAAAgAA

	AAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAB

	AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAA

	AAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAEYB

	AAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAA

	BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAA

	AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAB

	AAAAAAAAAAEAAAAAAAAAAAADAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAABAAAAAAAA

	AAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEA

	AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA

	AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAA

	AAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAA

	AAB4AAAAAAAAAPAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAGQAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAeAAAAAAAAADwAAAAAAAAAPAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA

	AAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA

	AAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAQAAAAAAAABkAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAA

	AAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAABkAAAAAAAAAAAAAAAAAAAAAQAAAAAA

	AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAA

	AAAAAAAAAAAA/////wAAAAABAQEBAQEBAAEBAQABAQAAAQEBAQEBAQABAQEAAQAAAQEB

	AAAAAQABAAABAAABAQEAAAAAAQAAAAEBAAEBAQEBAQABAQEBAQEBAQAAAQEBAAEAAQEB

	AQEBAAEAAQEBAQEBAQABAQEBAQABAAEAAAEBAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEB

	AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB

	AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAQEBAQEAAAEAAAEAAAEBAQEBAAAA

	AAEBAQEBAQEBAQEAAAEBAQEBAQEAAAEBAQEBAQAAAQEBAQABAQEBAQEBAQEBAAEAAQEA

	AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAQEAAAEAAQEBAQEAAQEBAQAAAQAB

	AQABAQEBAAAAAAABAQEBAQEBAAAAAQEAAQEBAQEBAQEBAQEBAQEBAQABAAEBAAEBAQEB

	AQEBAQEBAAEAAAEBAQAAAAABAQABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAA

	AAEBAQEBAAEAAQEAAAAAAAABAQABAQEBAQEBAAEAAAABAQABAQEBAQEBAQEBAQAAAAEB

	AQEAAAAAAAABAQEBAQEBAQEAAAAAAAEBAQEBAQEBAAEBAQEBAQEAAAAAAAAAAQEBAQEB

	</data>

	<key>CacheExtra</key>

	<dict>

		<key>oBbtJ8x+s1q0OkaiocPuog</key>

		<data>

		OAQAAIAHAABGAQAAAABAQAAAAAAJAAAA

		</data>

		<key>96GRvvjuBKkU4HzNsYcHPA</key>

		<string>12.5.0</string>

		<key>wYMBabAO8VguyDDVgCsPdg</key>

		<string>s=C5</string>

		<key>TZ/0j62wM3D0CuRt+Nc/Lw</key>

		<data>

		2nQ/38wqIpgsSWHgZHSpuqR4dSs=

		</data>

		<key>VuGdqp8UBpi9vPWHlPluVQ</key>

		<array>

			<string>$ProductType</string>

		</array>

		<key>xUHcyT2/HE8oi/4LaOI+Sw</key>

		<string>GUID_partition_scheme</string>

		<key>NaA/zJV7myg2w4YNmSe4yQ</key>

		<string>4350</string>

		<key>DViRIxZ/ZwO007CLcEYvZw</key>

		<string></string>

		<key>QbQzuIbef01P4JeoL9EmKg</key>

		<real>1</real>

		<key>gBw7IWiBnLHaA+lBrZBgWw</key>

		<integer>999</integer>

		<key>pB5sZVvnp+QjZQtt2KfQvA</key>

		<string>mav13</string>

		<key>qwXfFvH5jPXPxrny0XuGtQ</key>

		<string>A050C1D0-4316-11EF-8081-926F5BFCDD03</string>

		<key>zHeENZu+wbg7PUprwNwBWg</key>

		<string>ZD/A</string>

		<key>LeSRsiLoJCMhjn6nd6GWbQ</key>

		<string>iBoot-7459.140.15</string>

		<key>9MZ5AdH43csAUajl/dU+IQ</key>

		<array>

			<integer>1</integer>

		</array>

		<key>JhEU414EIaDvAz8ki5DSqw</key>

		<string>#e1ccb7</string>

		<key>+3Uf0Pm5F8Xy7Onyvko0vA</key>

		<string>iPhone</string>

		<key>Z/dqyWS6OZTRy10UcmUAhw</key>

		<string>iPhone 6s Plus</string>

		<key>Nzu4E/VsXjEIa83CkRdZrQ</key>

		<string>sha1</string>

		<key>91LyMcx4z1w3SGVeqteMnA</key>

		<data>

		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

		AAAAAAAAAAAAAAAAAAAAAAAAAA==

		</data>

		<key>JUWcn+5Ss0nvr5w/jk4WEg</key>

		<string>iPhone</string>

		<key>rkqlwPcRHwixY4gapPjanw</key>

		<string>iPhone</string>

		<key>IMLaTlxS7ITtwfbRfPYWuA</key>

		<string>B</string>

		<key>4qfpxrvLtWillIHpIsVgMA</key>

		<string>094F50BA-9BD4-4707-B1C1-8D698EDBA07C</string>

		<key>h63QSdBCiT/z0WU6rdQv6Q</key>

		<string>ZD</string>

		<key>qNNddlUK+B/YlooNoymwgA</key>

		<string>$iOSVersion</string>

		<key>k7QIBwZJJOVw+Sej/8h8VA</key>

		<string>arm64</string>

		<key>mZfUC7qo4pURNhyMHZ62RQ</key>

		<string>$BuildNumber</string>

		<key>ivIu8YTDnBSrYv/SN4G8Ag</key>

		<string>iPhone OS</string>

		<key>4W7X4OWHjri5PGaAGsCWxw</key>

		<integer>52</integer>

		<key>emXA9B552rnSoI7xXE91DA</key>

		<real>1</real>

		<key>NUYAz1eq3Flzt7ZQxXC/ng</key>

		<real>1</real>

		<key>97JDvERpVwO+GHtthIh7hA</key>

		<string>$Model</string>

		<key>oPeik/9e8lQWMszEjbPzng</key>

		<dict>

			<key>ArtworkDeviceIdiom</key>

			<string>phone</string>

			<key>ArtworkDeviceSubType</key>

			<integer>570</integer>

			<key>GraphicsFeatureSetFallbacks</key>

			<string>APPLE3v1:APPLE2:APPLE1:GLES2,0</string>

			<key>CompatibleDeviceFallback</key>

			<string>0</string>

			<key>ArtworkDisplayGamut</key>

			<string>sRGB</string>

			<key>ArtworkDeviceProductDescription</key>

			<string>iPhone 6s Plus</string>

			<key>ArtworkDynamicDisplayMode</key>

			<string>0</string>

			<key>GraphicsFeatureSetClass</key>

			<string>APPLE3</string>

			<key>ArtworkDeviceScaleFactor</key>

			<integer>3</integer>

			<key>DevicePerformanceMemoryClass</key>

			<integer>2</integer>

		</dict>

		<key>ybGkijAwLTwevankfVzsDQ</key>

		<data>

		AAAAAADgkEAAAAAAAACeQAAAAAAAaJNAAAAAAABAoUA=

		</data>

		<key>9s45ldrCC1WF+7b6C4H2BA</key>

		<string>iPhone</string>

		<key>LTI8wHvEYKy8zR1IXBW1uQ</key>

		<string>sRGB</string>

		<key>AoKnINTLPoKML3ctoP0AZg</key>

		<dict>

			<key>media-compression</key>

			<false/>

			<key>universal-lossy-buffer-compression</key>

			<false/>

			<key>buffer-compression</key>

			<false/>

			<key>universal-buffer-compression</key>

			<false/>

		</dict>

		<key>bbtR9jQx50Fv5Af/affNtA</key>

		<string>iPhone 6s Plus</string>

		<key>nSo8opze5rFk+EdBoR6tBw</key>

		<array>

			<string>CU</string>

			<string>IR</string>

			<string>SD</string>

			<string>SY</string>

			<string>KP</string>

		</array>

		<key>HXTqT3UXOKuTEklxz+wMAA</key>

		<data>

		HgAAAE9JUEd3AAAAAAEAAA==

		</data>

		<key>5pYKlGnYYBzGvAlIU8RjEQ</key>

		<string>$CPU</string>

		<key>h9jDsbgj7xIVeIQ8S3/X3Q</key>

		<string>$ProductType</string>

		<key>mumHZHMLEfAuTkkd28fHlQ</key>

		<string>#e4e7e8</string>

		<key>k+KTni1jrwErpcDMEnn3aw</key>

		<string>1351</string>

		<key>/YYygAofPDbhrwToVsXdeA</key>

		<string>$Hardware</string>

		<key>c7fCSBIbX1mFaRoKT5zTIw</key>

		<string>USI</string>

	</dict>

	<key>CacheVersion</key>

	<string>$BuildNumber</string>

</dict>

</plist>

";