name: Build EXE

on:
  push:
    branches: [ "main" ]

env:
  # هذا السطر يحل مشكلة التنبيه التي ظهرت لك بخصوص Node.js 24
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      # سنستخدم أمر البحث التلقائي عن ملف sln لضمان النجاح
      run: |
        $slnFile = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
        nuget restore $slnFile.FullName

    - name: Build Solution
      run: |
        $slnFile = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
        msbuild $slnFile.FullName /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: iSkorpion-Bypass-EXE
        path: |
          **/bin/Release/**/*.exe
          **/bin/Debug/**/*.exe
          **/*.dll

